/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompassRouteImport } from './routes/compass'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as ToolsVendorEvaluationMatrixRouteImport } from './routes/tools.vendor-evaluation-matrix'
import { Route as ToolsSoftwareBuyingChecklistRouteImport } from './routes/tools.software-buying-checklist'
import { Route as ToolsSmePricingGuideRouteImport } from './routes/tools.sme-pricing-guide'
import { Route as ToolsRequirementsWorkshopGuideRouteImport } from './routes/tools.requirements-workshop-guide'
import { Route as ToolsProjectRiskChecklistRouteImport } from './routes/tools.project-risk-checklist'
import { Route as ToolsProcessImprovementScorecardRouteImport } from './routes/tools.process-improvement-scorecard'
import { Route as ToolsMeetingAgendaTemplatesRouteImport } from './routes/tools.meeting-agenda-templates'
import { Route as ToolsDigitalTransformationRoadmapRouteImport } from './routes/tools.digital-transformation-roadmap'
import { Route as ToolsBusinessSystemsAuditRouteImport } from './routes/tools.business-systems-audit'
import { Route as ToolsBusinessDiscoveryChecklistRouteImport } from './routes/tools.business-discovery-checklist'
import { Route as ToolsAiReadinessAssessmentRouteImport } from './routes/tools.ai-readiness-assessment'
import { Route as SolutionsPartnerRouteImport } from './routes/solutions.partner'
import { Route as SolutionsLaunchRouteImport } from './routes/solutions.launch'
import { Route as SolutionsGrowthRouteImport } from './routes/solutions.growth'
import { Route as SolutionsFlowRouteImport } from './routes/solutions.flow'
import { Route as SolutionsAccelerateRouteImport } from './routes/solutions.accelerate'
import { Route as SessionsStrategicRouteImport } from './routes/sessions.strategic'
import { Route as SessionsProfessionalRouteImport } from './routes/sessions.professional'
import { Route as SessionsHistoryRouteImport } from './routes/sessions.history'
import { Route as SessionsEssentialRouteImport } from './routes/sessions.essential'
import { Route as ResourcesSectionRouteImport } from './routes/resources.$section'
import { Route as DocumentsScopeOfWorkRouteImport } from './routes/documents.scope-of-work'
import { Route as DocumentsProposalTemplateRouteImport } from './routes/documents.proposal-template'
import { Route as DocumentsInvoiceTemplateRouteImport } from './routes/documents.invoice-template'
import { Route as DocumentsCompassReportRouteImport } from './routes/documents.compass-report'
import { Route as DocumentsClientWelcomePackRouteImport } from './routes/documents.client-welcome-pack'
import { Route as DocumentsClientContractRouteImport } from './routes/documents.client-contract'
import { Route as DocumentsBusinessPlanRouteImport } from './routes/documents.business-plan'
import { Route as ResourcesSectionIndexRouteImport } from './routes/resources.$section.index'
import { Route as ResourcesSectionArticleRouteImport } from './routes/resources.$section.$article'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassRoute = CompassRouteImport.update({
  id: '/compass',
  path: '/compass',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const ToolsVendorEvaluationMatrixRoute =
  ToolsVendorEvaluationMatrixRouteImport.update({
    id: '/tools/vendor-evaluation-matrix',
    path: '/tools/vendor-evaluation-matrix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSoftwareBuyingChecklistRoute =
  ToolsSoftwareBuyingChecklistRouteImport.update({
    id: '/tools/software-buying-checklist',
    path: '/tools/software-buying-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSmePricingGuideRoute = ToolsSmePricingGuideRouteImport.update({
  id: '/tools/sme-pricing-guide',
  path: '/tools/sme-pricing-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRequirementsWorkshopGuideRoute =
  ToolsRequirementsWorkshopGuideRouteImport.update({
    id: '/tools/requirements-workshop-guide',
    path: '/tools/requirements-workshop-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsProjectRiskChecklistRoute =
  ToolsProjectRiskChecklistRouteImport.update({
    id: '/tools/project-risk-checklist',
    path: '/tools/project-risk-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsProcessImprovementScorecardRoute =
  ToolsProcessImprovementScorecardRouteImport.update({
    id: '/tools/process-improvement-scorecard',
    path: '/tools/process-improvement-scorecard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsMeetingAgendaTemplatesRoute =
  ToolsMeetingAgendaTemplatesRouteImport.update({
    id: '/tools/meeting-agenda-templates',
    path: '/tools/meeting-agenda-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsDigitalTransformationRoadmapRoute =
  ToolsDigitalTransformationRoadmapRouteImport.update({
    id: '/tools/digital-transformation-roadmap',
    path: '/tools/digital-transformation-roadmap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsBusinessSystemsAuditRoute =
  ToolsBusinessSystemsAuditRouteImport.update({
    id: '/tools/business-systems-audit',
    path: '/tools/business-systems-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsBusinessDiscoveryChecklistRoute =
  ToolsBusinessDiscoveryChecklistRouteImport.update({
    id: '/tools/business-discovery-checklist',
    path: '/tools/business-discovery-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsAiReadinessAssessmentRoute =
  ToolsAiReadinessAssessmentRouteImport.update({
    id: '/tools/ai-readiness-assessment',
    path: '/tools/ai-readiness-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsPartnerRoute = SolutionsPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsLaunchRoute = SolutionsLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsGrowthRoute = SolutionsGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsFlowRoute = SolutionsFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAccelerateRoute = SolutionsAccelerateRouteImport.update({
  id: '/accelerate',
  path: '/accelerate',
  getParentRoute: () => SolutionsRoute,
} as any)
const SessionsStrategicRoute = SessionsStrategicRouteImport.update({
  id: '/strategic',
  path: '/strategic',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsProfessionalRoute = SessionsProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsHistoryRoute = SessionsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsEssentialRoute = SessionsEssentialRouteImport.update({
  id: '/essential',
  path: '/essential',
  getParentRoute: () => SessionsRoute,
} as any)
const ResourcesSectionRoute = ResourcesSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => ResourcesRoute,
} as any)
const DocumentsScopeOfWorkRoute = DocumentsScopeOfWorkRouteImport.update({
  id: '/scope-of-work',
  path: '/scope-of-work',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsProposalTemplateRoute =
  DocumentsProposalTemplateRouteImport.update({
    id: '/proposal-template',
    path: '/proposal-template',
    getParentRoute: () => DocumentsRoute,
  } as any)
const DocumentsInvoiceTemplateRoute =
  DocumentsInvoiceTemplateRouteImport.update({
    id: '/invoice-template',
    path: '/invoice-template',
    getParentRoute: () => DocumentsRoute,
  } as any)
const DocumentsCompassReportRoute = DocumentsCompassReportRouteImport.update({
  id: '/compass-report',
  path: '/compass-report',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsClientWelcomePackRoute =
  DocumentsClientWelcomePackRouteImport.update({
    id: '/client-welcome-pack',
    path: '/client-welcome-pack',
    getParentRoute: () => DocumentsRoute,
  } as any)
const DocumentsClientContractRoute = DocumentsClientContractRouteImport.update({
  id: '/client-contract',
  path: '/client-contract',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsBusinessPlanRoute = DocumentsBusinessPlanRouteImport.update({
  id: '/business-plan',
  path: '/business-plan',
  getParentRoute: () => DocumentsRoute,
} as any)
const ResourcesSectionIndexRoute = ResourcesSectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesSectionRoute,
} as any)
const ResourcesSectionArticleRoute = ResourcesSectionArticleRouteImport.update({
  id: '/$article',
  path: '/$article',
  getParentRoute: () => ResourcesSectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/compass': typeof CompassRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/documents/business-plan': typeof DocumentsBusinessPlanRoute
  '/documents/client-contract': typeof DocumentsClientContractRoute
  '/documents/client-welcome-pack': typeof DocumentsClientWelcomePackRoute
  '/documents/compass-report': typeof DocumentsCompassReportRoute
  '/documents/invoice-template': typeof DocumentsInvoiceTemplateRoute
  '/documents/proposal-template': typeof DocumentsProposalTemplateRoute
  '/documents/scope-of-work': typeof DocumentsScopeOfWorkRoute
  '/resources/$section': typeof ResourcesSectionRouteWithChildren
  '/sessions/essential': typeof SessionsEssentialRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/sessions/professional': typeof SessionsProfessionalRoute
  '/sessions/strategic': typeof SessionsStrategicRoute
  '/solutions/accelerate': typeof SolutionsAccelerateRoute
  '/solutions/flow': typeof SolutionsFlowRoute
  '/solutions/growth': typeof SolutionsGrowthRoute
  '/solutions/launch': typeof SolutionsLaunchRoute
  '/solutions/partner': typeof SolutionsPartnerRoute
  '/tools/ai-readiness-assessment': typeof ToolsAiReadinessAssessmentRoute
  '/tools/business-discovery-checklist': typeof ToolsBusinessDiscoveryChecklistRoute
  '/tools/business-systems-audit': typeof ToolsBusinessSystemsAuditRoute
  '/tools/digital-transformation-roadmap': typeof ToolsDigitalTransformationRoadmapRoute
  '/tools/meeting-agenda-templates': typeof ToolsMeetingAgendaTemplatesRoute
  '/tools/process-improvement-scorecard': typeof ToolsProcessImprovementScorecardRoute
  '/tools/project-risk-checklist': typeof ToolsProjectRiskChecklistRoute
  '/tools/requirements-workshop-guide': typeof ToolsRequirementsWorkshopGuideRoute
  '/tools/sme-pricing-guide': typeof ToolsSmePricingGuideRoute
  '/tools/software-buying-checklist': typeof ToolsSoftwareBuyingChecklistRoute
  '/tools/vendor-evaluation-matrix': typeof ToolsVendorEvaluationMatrixRoute
  '/documents/': typeof DocumentsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/$section/$article': typeof ResourcesSectionArticleRoute
  '/resources/$section/': typeof ResourcesSectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/compass': typeof CompassRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/documents/business-plan': typeof DocumentsBusinessPlanRoute
  '/documents/client-contract': typeof DocumentsClientContractRoute
  '/documents/client-welcome-pack': typeof DocumentsClientWelcomePackRoute
  '/documents/compass-report': typeof DocumentsCompassReportRoute
  '/documents/invoice-template': typeof DocumentsInvoiceTemplateRoute
  '/documents/proposal-template': typeof DocumentsProposalTemplateRoute
  '/documents/scope-of-work': typeof DocumentsScopeOfWorkRoute
  '/sessions/essential': typeof SessionsEssentialRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/sessions/professional': typeof SessionsProfessionalRoute
  '/sessions/strategic': typeof SessionsStrategicRoute
  '/solutions/accelerate': typeof SolutionsAccelerateRoute
  '/solutions/flow': typeof SolutionsFlowRoute
  '/solutions/growth': typeof SolutionsGrowthRoute
  '/solutions/launch': typeof SolutionsLaunchRoute
  '/solutions/partner': typeof SolutionsPartnerRoute
  '/tools/ai-readiness-assessment': typeof ToolsAiReadinessAssessmentRoute
  '/tools/business-discovery-checklist': typeof ToolsBusinessDiscoveryChecklistRoute
  '/tools/business-systems-audit': typeof ToolsBusinessSystemsAuditRoute
  '/tools/digital-transformation-roadmap': typeof ToolsDigitalTransformationRoadmapRoute
  '/tools/meeting-agenda-templates': typeof ToolsMeetingAgendaTemplatesRoute
  '/tools/process-improvement-scorecard': typeof ToolsProcessImprovementScorecardRoute
  '/tools/project-risk-checklist': typeof ToolsProjectRiskChecklistRoute
  '/tools/requirements-workshop-guide': typeof ToolsRequirementsWorkshopGuideRoute
  '/tools/sme-pricing-guide': typeof ToolsSmePricingGuideRoute
  '/tools/software-buying-checklist': typeof ToolsSoftwareBuyingChecklistRoute
  '/tools/vendor-evaluation-matrix': typeof ToolsVendorEvaluationMatrixRoute
  '/documents': typeof DocumentsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/resources/$section/$article': typeof ResourcesSectionArticleRoute
  '/resources/$section': typeof ResourcesSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/compass': typeof CompassRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/documents/business-plan': typeof DocumentsBusinessPlanRoute
  '/documents/client-contract': typeof DocumentsClientContractRoute
  '/documents/client-welcome-pack': typeof DocumentsClientWelcomePackRoute
  '/documents/compass-report': typeof DocumentsCompassReportRoute
  '/documents/invoice-template': typeof DocumentsInvoiceTemplateRoute
  '/documents/proposal-template': typeof DocumentsProposalTemplateRoute
  '/documents/scope-of-work': typeof DocumentsScopeOfWorkRoute
  '/resources/$section': typeof ResourcesSectionRouteWithChildren
  '/sessions/essential': typeof SessionsEssentialRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/sessions/professional': typeof SessionsProfessionalRoute
  '/sessions/strategic': typeof SessionsStrategicRoute
  '/solutions/accelerate': typeof SolutionsAccelerateRoute
  '/solutions/flow': typeof SolutionsFlowRoute
  '/solutions/growth': typeof SolutionsGrowthRoute
  '/solutions/launch': typeof SolutionsLaunchRoute
  '/solutions/partner': typeof SolutionsPartnerRoute
  '/tools/ai-readiness-assessment': typeof ToolsAiReadinessAssessmentRoute
  '/tools/business-discovery-checklist': typeof ToolsBusinessDiscoveryChecklistRoute
  '/tools/business-systems-audit': typeof ToolsBusinessSystemsAuditRoute
  '/tools/digital-transformation-roadmap': typeof ToolsDigitalTransformationRoadmapRoute
  '/tools/meeting-agenda-templates': typeof ToolsMeetingAgendaTemplatesRoute
  '/tools/process-improvement-scorecard': typeof ToolsProcessImprovementScorecardRoute
  '/tools/project-risk-checklist': typeof ToolsProjectRiskChecklistRoute
  '/tools/requirements-workshop-guide': typeof ToolsRequirementsWorkshopGuideRoute
  '/tools/sme-pricing-guide': typeof ToolsSmePricingGuideRoute
  '/tools/software-buying-checklist': typeof ToolsSoftwareBuyingChecklistRoute
  '/tools/vendor-evaluation-matrix': typeof ToolsVendorEvaluationMatrixRoute
  '/documents/': typeof DocumentsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/$section/$article': typeof ResourcesSectionArticleRoute
  '/resources/$section/': typeof ResourcesSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/compass'
    | '/contact'
    | '/cookies'
    | '/documents'
    | '/industries'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/sessions'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/documents/business-plan'
    | '/documents/client-contract'
    | '/documents/client-welcome-pack'
    | '/documents/compass-report'
    | '/documents/invoice-template'
    | '/documents/proposal-template'
    | '/documents/scope-of-work'
    | '/resources/$section'
    | '/sessions/essential'
    | '/sessions/history'
    | '/sessions/professional'
    | '/sessions/strategic'
    | '/solutions/accelerate'
    | '/solutions/flow'
    | '/solutions/growth'
    | '/solutions/launch'
    | '/solutions/partner'
    | '/tools/ai-readiness-assessment'
    | '/tools/business-discovery-checklist'
    | '/tools/business-systems-audit'
    | '/tools/digital-transformation-roadmap'
    | '/tools/meeting-agenda-templates'
    | '/tools/process-improvement-scorecard'
    | '/tools/project-risk-checklist'
    | '/tools/requirements-workshop-guide'
    | '/tools/sme-pricing-guide'
    | '/tools/software-buying-checklist'
    | '/tools/vendor-evaluation-matrix'
    | '/documents/'
    | '/resources/'
    | '/resources/$section/$article'
    | '/resources/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/compass'
    | '/contact'
    | '/cookies'
    | '/industries'
    | '/pricing'
    | '/privacy'
    | '/sessions'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/documents/business-plan'
    | '/documents/client-contract'
    | '/documents/client-welcome-pack'
    | '/documents/compass-report'
    | '/documents/invoice-template'
    | '/documents/proposal-template'
    | '/documents/scope-of-work'
    | '/sessions/essential'
    | '/sessions/history'
    | '/sessions/professional'
    | '/sessions/strategic'
    | '/solutions/accelerate'
    | '/solutions/flow'
    | '/solutions/growth'
    | '/solutions/launch'
    | '/solutions/partner'
    | '/tools/ai-readiness-assessment'
    | '/tools/business-discovery-checklist'
    | '/tools/business-systems-audit'
    | '/tools/digital-transformation-roadmap'
    | '/tools/meeting-agenda-templates'
    | '/tools/process-improvement-scorecard'
    | '/tools/project-risk-checklist'
    | '/tools/requirements-workshop-guide'
    | '/tools/sme-pricing-guide'
    | '/tools/software-buying-checklist'
    | '/tools/vendor-evaluation-matrix'
    | '/documents'
    | '/resources'
    | '/resources/$section/$article'
    | '/resources/$section'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/compass'
    | '/contact'
    | '/cookies'
    | '/documents'
    | '/industries'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/sessions'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/documents/business-plan'
    | '/documents/client-contract'
    | '/documents/client-welcome-pack'
    | '/documents/compass-report'
    | '/documents/invoice-template'
    | '/documents/proposal-template'
    | '/documents/scope-of-work'
    | '/resources/$section'
    | '/sessions/essential'
    | '/sessions/history'
    | '/sessions/professional'
    | '/sessions/strategic'
    | '/solutions/accelerate'
    | '/solutions/flow'
    | '/solutions/growth'
    | '/solutions/launch'
    | '/solutions/partner'
    | '/tools/ai-readiness-assessment'
    | '/tools/business-discovery-checklist'
    | '/tools/business-systems-audit'
    | '/tools/digital-transformation-roadmap'
    | '/tools/meeting-agenda-templates'
    | '/tools/process-improvement-scorecard'
    | '/tools/project-risk-checklist'
    | '/tools/requirements-workshop-guide'
    | '/tools/sme-pricing-guide'
    | '/tools/software-buying-checklist'
    | '/tools/vendor-evaluation-matrix'
    | '/documents/'
    | '/resources/'
    | '/resources/$section/$article'
    | '/resources/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CompassRoute: typeof CompassRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SessionsRoute: typeof SessionsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
  ToolsAiReadinessAssessmentRoute: typeof ToolsAiReadinessAssessmentRoute
  ToolsBusinessDiscoveryChecklistRoute: typeof ToolsBusinessDiscoveryChecklistRoute
  ToolsBusinessSystemsAuditRoute: typeof ToolsBusinessSystemsAuditRoute
  ToolsDigitalTransformationRoadmapRoute: typeof ToolsDigitalTransformationRoadmapRoute
  ToolsMeetingAgendaTemplatesRoute: typeof ToolsMeetingAgendaTemplatesRoute
  ToolsProcessImprovementScorecardRoute: typeof ToolsProcessImprovementScorecardRoute
  ToolsProjectRiskChecklistRoute: typeof ToolsProjectRiskChecklistRoute
  ToolsRequirementsWorkshopGuideRoute: typeof ToolsRequirementsWorkshopGuideRoute
  ToolsSmePricingGuideRoute: typeof ToolsSmePricingGuideRoute
  ToolsSoftwareBuyingChecklistRoute: typeof ToolsSoftwareBuyingChecklistRoute
  ToolsVendorEvaluationMatrixRoute: typeof ToolsVendorEvaluationMatrixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass': {
      id: '/compass'
      path: '/compass'
      fullPath: '/compass'
      preLoaderRoute: typeof CompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/tools/vendor-evaluation-matrix': {
      id: '/tools/vendor-evaluation-matrix'
      path: '/tools/vendor-evaluation-matrix'
      fullPath: '/tools/vendor-evaluation-matrix'
      preLoaderRoute: typeof ToolsVendorEvaluationMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/software-buying-checklist': {
      id: '/tools/software-buying-checklist'
      path: '/tools/software-buying-checklist'
      fullPath: '/tools/software-buying-checklist'
      preLoaderRoute: typeof ToolsSoftwareBuyingChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sme-pricing-guide': {
      id: '/tools/sme-pricing-guide'
      path: '/tools/sme-pricing-guide'
      fullPath: '/tools/sme-pricing-guide'
      preLoaderRoute: typeof ToolsSmePricingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/requirements-workshop-guide': {
      id: '/tools/requirements-workshop-guide'
      path: '/tools/requirements-workshop-guide'
      fullPath: '/tools/requirements-workshop-guide'
      preLoaderRoute: typeof ToolsRequirementsWorkshopGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/project-risk-checklist': {
      id: '/tools/project-risk-checklist'
      path: '/tools/project-risk-checklist'
      fullPath: '/tools/project-risk-checklist'
      preLoaderRoute: typeof ToolsProjectRiskChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/process-improvement-scorecard': {
      id: '/tools/process-improvement-scorecard'
      path: '/tools/process-improvement-scorecard'
      fullPath: '/tools/process-improvement-scorecard'
      preLoaderRoute: typeof ToolsProcessImprovementScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/meeting-agenda-templates': {
      id: '/tools/meeting-agenda-templates'
      path: '/tools/meeting-agenda-templates'
      fullPath: '/tools/meeting-agenda-templates'
      preLoaderRoute: typeof ToolsMeetingAgendaTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/digital-transformation-roadmap': {
      id: '/tools/digital-transformation-roadmap'
      path: '/tools/digital-transformation-roadmap'
      fullPath: '/tools/digital-transformation-roadmap'
      preLoaderRoute: typeof ToolsDigitalTransformationRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/business-systems-audit': {
      id: '/tools/business-systems-audit'
      path: '/tools/business-systems-audit'
      fullPath: '/tools/business-systems-audit'
      preLoaderRoute: typeof ToolsBusinessSystemsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/business-discovery-checklist': {
      id: '/tools/business-discovery-checklist'
      path: '/tools/business-discovery-checklist'
      fullPath: '/tools/business-discovery-checklist'
      preLoaderRoute: typeof ToolsBusinessDiscoveryChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ai-readiness-assessment': {
      id: '/tools/ai-readiness-assessment'
      path: '/tools/ai-readiness-assessment'
      fullPath: '/tools/ai-readiness-assessment'
      preLoaderRoute: typeof ToolsAiReadinessAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/partner': {
      id: '/solutions/partner'
      path: '/partner'
      fullPath: '/solutions/partner'
      preLoaderRoute: typeof SolutionsPartnerRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/launch': {
      id: '/solutions/launch'
      path: '/launch'
      fullPath: '/solutions/launch'
      preLoaderRoute: typeof SolutionsLaunchRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/growth': {
      id: '/solutions/growth'
      path: '/growth'
      fullPath: '/solutions/growth'
      preLoaderRoute: typeof SolutionsGrowthRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/flow': {
      id: '/solutions/flow'
      path: '/flow'
      fullPath: '/solutions/flow'
      preLoaderRoute: typeof SolutionsFlowRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/accelerate': {
      id: '/solutions/accelerate'
      path: '/accelerate'
      fullPath: '/solutions/accelerate'
      preLoaderRoute: typeof SolutionsAccelerateRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/sessions/strategic': {
      id: '/sessions/strategic'
      path: '/strategic'
      fullPath: '/sessions/strategic'
      preLoaderRoute: typeof SessionsStrategicRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/professional': {
      id: '/sessions/professional'
      path: '/professional'
      fullPath: '/sessions/professional'
      preLoaderRoute: typeof SessionsProfessionalRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/history': {
      id: '/sessions/history'
      path: '/history'
      fullPath: '/sessions/history'
      preLoaderRoute: typeof SessionsHistoryRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/essential': {
      id: '/sessions/essential'
      path: '/essential'
      fullPath: '/sessions/essential'
      preLoaderRoute: typeof SessionsEssentialRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/resources/$section': {
      id: '/resources/$section'
      path: '/$section'
      fullPath: '/resources/$section'
      preLoaderRoute: typeof ResourcesSectionRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/documents/scope-of-work': {
      id: '/documents/scope-of-work'
      path: '/scope-of-work'
      fullPath: '/documents/scope-of-work'
      preLoaderRoute: typeof DocumentsScopeOfWorkRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/proposal-template': {
      id: '/documents/proposal-template'
      path: '/proposal-template'
      fullPath: '/documents/proposal-template'
      preLoaderRoute: typeof DocumentsProposalTemplateRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/invoice-template': {
      id: '/documents/invoice-template'
      path: '/invoice-template'
      fullPath: '/documents/invoice-template'
      preLoaderRoute: typeof DocumentsInvoiceTemplateRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/compass-report': {
      id: '/documents/compass-report'
      path: '/compass-report'
      fullPath: '/documents/compass-report'
      preLoaderRoute: typeof DocumentsCompassReportRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/client-welcome-pack': {
      id: '/documents/client-welcome-pack'
      path: '/client-welcome-pack'
      fullPath: '/documents/client-welcome-pack'
      preLoaderRoute: typeof DocumentsClientWelcomePackRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/client-contract': {
      id: '/documents/client-contract'
      path: '/client-contract'
      fullPath: '/documents/client-contract'
      preLoaderRoute: typeof DocumentsClientContractRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/business-plan': {
      id: '/documents/business-plan'
      path: '/business-plan'
      fullPath: '/documents/business-plan'
      preLoaderRoute: typeof DocumentsBusinessPlanRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/resources/$section/': {
      id: '/resources/$section/'
      path: '/'
      fullPath: '/resources/$section/'
      preLoaderRoute: typeof ResourcesSectionIndexRouteImport
      parentRoute: typeof ResourcesSectionRoute
    }
    '/resources/$section/$article': {
      id: '/resources/$section/$article'
      path: '/$article'
      fullPath: '/resources/$section/$article'
      preLoaderRoute: typeof ResourcesSectionArticleRouteImport
      parentRoute: typeof ResourcesSectionRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsBusinessPlanRoute: typeof DocumentsBusinessPlanRoute
  DocumentsClientContractRoute: typeof DocumentsClientContractRoute
  DocumentsClientWelcomePackRoute: typeof DocumentsClientWelcomePackRoute
  DocumentsCompassReportRoute: typeof DocumentsCompassReportRoute
  DocumentsInvoiceTemplateRoute: typeof DocumentsInvoiceTemplateRoute
  DocumentsProposalTemplateRoute: typeof DocumentsProposalTemplateRoute
  DocumentsScopeOfWorkRoute: typeof DocumentsScopeOfWorkRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsBusinessPlanRoute: DocumentsBusinessPlanRoute,
  DocumentsClientContractRoute: DocumentsClientContractRoute,
  DocumentsClientWelcomePackRoute: DocumentsClientWelcomePackRoute,
  DocumentsCompassReportRoute: DocumentsCompassReportRoute,
  DocumentsInvoiceTemplateRoute: DocumentsInvoiceTemplateRoute,
  DocumentsProposalTemplateRoute: DocumentsProposalTemplateRoute,
  DocumentsScopeOfWorkRoute: DocumentsScopeOfWorkRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface ResourcesSectionRouteChildren {
  ResourcesSectionArticleRoute: typeof ResourcesSectionArticleRoute
  ResourcesSectionIndexRoute: typeof ResourcesSectionIndexRoute
}

const ResourcesSectionRouteChildren: ResourcesSectionRouteChildren = {
  ResourcesSectionArticleRoute: ResourcesSectionArticleRoute,
  ResourcesSectionIndexRoute: ResourcesSectionIndexRoute,
}

const ResourcesSectionRouteWithChildren =
  ResourcesSectionRoute._addFileChildren(ResourcesSectionRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSectionRoute: typeof ResourcesSectionRouteWithChildren
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSectionRoute: ResourcesSectionRouteWithChildren,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SessionsRouteChildren {
  SessionsEssentialRoute: typeof SessionsEssentialRoute
  SessionsHistoryRoute: typeof SessionsHistoryRoute
  SessionsProfessionalRoute: typeof SessionsProfessionalRoute
  SessionsStrategicRoute: typeof SessionsStrategicRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsEssentialRoute: SessionsEssentialRoute,
  SessionsHistoryRoute: SessionsHistoryRoute,
  SessionsProfessionalRoute: SessionsProfessionalRoute,
  SessionsStrategicRoute: SessionsStrategicRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsAccelerateRoute: typeof SolutionsAccelerateRoute
  SolutionsFlowRoute: typeof SolutionsFlowRoute
  SolutionsGrowthRoute: typeof SolutionsGrowthRoute
  SolutionsLaunchRoute: typeof SolutionsLaunchRoute
  SolutionsPartnerRoute: typeof SolutionsPartnerRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAccelerateRoute: SolutionsAccelerateRoute,
  SolutionsFlowRoute: SolutionsFlowRoute,
  SolutionsGrowthRoute: SolutionsGrowthRoute,
  SolutionsLaunchRoute: SolutionsLaunchRoute,
  SolutionsPartnerRoute: SolutionsPartnerRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CompassRoute: CompassRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SessionsRoute: SessionsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
  ToolsAiReadinessAssessmentRoute: ToolsAiReadinessAssessmentRoute,
  ToolsBusinessDiscoveryChecklistRoute: ToolsBusinessDiscoveryChecklistRoute,
  ToolsBusinessSystemsAuditRoute: ToolsBusinessSystemsAuditRoute,
  ToolsDigitalTransformationRoadmapRoute:
    ToolsDigitalTransformationRoadmapRoute,
  ToolsMeetingAgendaTemplatesRoute: ToolsMeetingAgendaTemplatesRoute,
  ToolsProcessImprovementScorecardRoute: ToolsProcessImprovementScorecardRoute,
  ToolsProjectRiskChecklistRoute: ToolsProjectRiskChecklistRoute,
  ToolsRequirementsWorkshopGuideRoute: ToolsRequirementsWorkshopGuideRoute,
  ToolsSmePricingGuideRoute: ToolsSmePricingGuideRoute,
  ToolsSoftwareBuyingChecklistRoute: ToolsSoftwareBuyingChecklistRoute,
  ToolsVendorEvaluationMatrixRoute: ToolsVendorEvaluationMatrixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
