/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompassRouteImport } from './routes/compass'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsPartnerRouteImport } from './routes/solutions.partner'
import { Route as SolutionsLaunchRouteImport } from './routes/solutions.launch'
import { Route as SolutionsGrowthRouteImport } from './routes/solutions.growth'
import { Route as SolutionsFlowRouteImport } from './routes/solutions.flow'
import { Route as SolutionsAccelerateRouteImport } from './routes/solutions.accelerate'
import { Route as ResourcesSectionRouteImport } from './routes/resources.$section'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassRoute = CompassRouteImport.update({
  id: '/compass',
  path: '/compass',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPartnerRoute = SolutionsPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsLaunchRoute = SolutionsLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsGrowthRoute = SolutionsGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsFlowRoute = SolutionsFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAccelerateRoute = SolutionsAccelerateRouteImport.update({
  id: '/accelerate',
  path: '/accelerate',
  getParentRoute: () => SolutionsRoute,
} as any)
const ResourcesSectionRoute = ResourcesSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/compass': typeof CompassRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/resources/$section': typeof ResourcesSectionRoute
  '/solutions/accelerate': typeof SolutionsAccelerateRoute
  '/solutions/flow': typeof SolutionsFlowRoute
  '/solutions/growth': typeof SolutionsGrowthRoute
  '/solutions/launch': typeof SolutionsLaunchRoute
  '/solutions/partner': typeof SolutionsPartnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/compass': typeof CompassRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/resources/$section': typeof ResourcesSectionRoute
  '/solutions/accelerate': typeof SolutionsAccelerateRoute
  '/solutions/flow': typeof SolutionsFlowRoute
  '/solutions/growth': typeof SolutionsGrowthRoute
  '/solutions/launch': typeof SolutionsLaunchRoute
  '/solutions/partner': typeof SolutionsPartnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/compass': typeof CompassRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/resources/$section': typeof ResourcesSectionRoute
  '/solutions/accelerate': typeof SolutionsAccelerateRoute
  '/solutions/flow': typeof SolutionsFlowRoute
  '/solutions/growth': typeof SolutionsGrowthRoute
  '/solutions/launch': typeof SolutionsLaunchRoute
  '/solutions/partner': typeof SolutionsPartnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/compass'
    | '/contact'
    | '/cookies'
    | '/industries'
    | '/privacy'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/resources/$section'
    | '/solutions/accelerate'
    | '/solutions/flow'
    | '/solutions/growth'
    | '/solutions/launch'
    | '/solutions/partner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/compass'
    | '/contact'
    | '/cookies'
    | '/industries'
    | '/privacy'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/resources/$section'
    | '/solutions/accelerate'
    | '/solutions/flow'
    | '/solutions/growth'
    | '/solutions/launch'
    | '/solutions/partner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/compass'
    | '/contact'
    | '/cookies'
    | '/industries'
    | '/privacy'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/resources/$section'
    | '/solutions/accelerate'
    | '/solutions/flow'
    | '/solutions/growth'
    | '/solutions/launch'
    | '/solutions/partner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CompassRoute: typeof CompassRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass': {
      id: '/compass'
      path: '/compass'
      fullPath: '/compass'
      preLoaderRoute: typeof CompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/partner': {
      id: '/solutions/partner'
      path: '/partner'
      fullPath: '/solutions/partner'
      preLoaderRoute: typeof SolutionsPartnerRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/launch': {
      id: '/solutions/launch'
      path: '/launch'
      fullPath: '/solutions/launch'
      preLoaderRoute: typeof SolutionsLaunchRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/growth': {
      id: '/solutions/growth'
      path: '/growth'
      fullPath: '/solutions/growth'
      preLoaderRoute: typeof SolutionsGrowthRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/flow': {
      id: '/solutions/flow'
      path: '/flow'
      fullPath: '/solutions/flow'
      preLoaderRoute: typeof SolutionsFlowRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/accelerate': {
      id: '/solutions/accelerate'
      path: '/accelerate'
      fullPath: '/solutions/accelerate'
      preLoaderRoute: typeof SolutionsAccelerateRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/resources/$section': {
      id: '/resources/$section'
      path: '/$section'
      fullPath: '/resources/$section'
      preLoaderRoute: typeof ResourcesSectionRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSectionRoute: typeof ResourcesSectionRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSectionRoute: ResourcesSectionRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsAccelerateRoute: typeof SolutionsAccelerateRoute
  SolutionsFlowRoute: typeof SolutionsFlowRoute
  SolutionsGrowthRoute: typeof SolutionsGrowthRoute
  SolutionsLaunchRoute: typeof SolutionsLaunchRoute
  SolutionsPartnerRoute: typeof SolutionsPartnerRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAccelerateRoute: SolutionsAccelerateRoute,
  SolutionsFlowRoute: SolutionsFlowRoute,
  SolutionsGrowthRoute: SolutionsGrowthRoute,
  SolutionsLaunchRoute: SolutionsLaunchRoute,
  SolutionsPartnerRoute: SolutionsPartnerRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CompassRoute: CompassRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
